
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 24 21:32:10 EDT 2009
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface ClojureSym {
  /* terminals */
  public static final int NUM_BIG_DECIMAL = 23;
  public static final int LINE_COMMENT = 34;
  public static final int STRING_LITERAL = 50;
  public static final int RIGHT_PAREN = 3;
  public static final int SHARP_UP = 25;
  public static final int RIGHT_BRACKET = 7;
  public static final int RATIO_NUMBER = 24;
  public static final int STRING_CONTENT = 31;
  public static final int CHAR = 29;
  public static final int OTHER = 37;
  public static final int SHARP_HAT = 10;
  public static final int NUM_INT = 18;
  public static final int TILDE = 15;
  public static final int BACK_QUOTE = 14;
  public static final int BOOLEAN_LITERAL = 48;
  public static final int CHARACTER_LITERAL = 49;
  public static final int NIL = 43;
  public static final int SLASH_LETTER = 36;
  public static final int LEFT_BRACE = 4;
  public static final int NULL_LITERAL = 51;
  public static final int IMPLICIT_ARG = 26;
  public static final int EOF = 0;
  public static final int NoDigit1 = 40;
  public static final int DOUBLE_QUOTE = 12;
  public static final int ONE_NL = 27;
  public static final int KEYWORD = 11;
  public static final int TRUE = 44;
  public static final int error = 1;
  public static final int NoDigit = 38;
  public static final int HAT = 9;
  public static final int NUM_BIG_INT = 20;
  public static final int RIGHT_BRACE = 5;
  public static final int TILDE_AT = 17;
  public static final int IDENT = 41;
  public static final int SINGLE_QUOTE = 13;
  public static final int STRING_ESC = 30;
  public static final int FLOATING_POINT_LITERAL = 47;
  public static final int SHARP = 8;
  public static final int LETTER = 35;
  public static final int HEX_DIGIT = 28;
  public static final int LEFT_PAREN = 2;
  public static final int KEY = 42;
  public static final int STRING = 32;
  public static final int OTHER_REDUCED = 39;
  public static final int NUM_DOUBLE = 22;
  public static final int NUM_LONG = 19;
  public static final int AT = 16;
  public static final int NUM_FLOAT = 21;
  public static final int FALSE = 45;
  public static final int LEFT_BRACKET = 6;
  public static final int WRONG_STRING = 33;
  public static final int INTEGER_LITERAL = 46;
}

