
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 16 10:38:42 EST 2010
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface ClojureSym {
  /* terminals */
  public static final int AT = 53;
  public static final int RECUR = 41;
  public static final int LETFN = 47;
  public static final int NUM_INT_PART = 13;
  public static final int NEWLINE = 2;
  public static final int RIGHT_PAREN = 21;
  public static final int RIGHT_SQUARE = 23;
  public static final int COMMA = 4;
  public static final int DOUBLE_LITERAL = 84;
  public static final int NUM_BIG_DECIMAL = 19;
  public static final int DISP_DISCARD_FORM = 35;
  public static final int NUM_DOUBLE = 18;
  public static final int FN = 39;
  public static final int IMPLICIT_ARG = 51;
  public static final int LOOP = 40;
  public static final int WRONG_STRING_LITERAL = 89;
  public static final int INTEGER_LITERAL = 80;
  public static final int FALSE = 72;
  public static final int LEFT_CURLY = 24;
  public static final int DEF = 37;
  public static final int NIL = 70;
  public static final int TILDA = 52;
  public static final int RATIO = 86;
  public static final int ONE_NL = 55;
  public static final int BAD_CHARACTER = 73;
  public static final int OTHER_REDUCED = 66;
  public static final int DISP_VAR = 28;
  public static final int DISPATCH = 26;
  public static final int OTHER = 64;
  public static final int TRUE = 71;
  public static final int NoDigit = 65;
  public static final int DISP_UNREADABLE = 34;
  public static final int LONG_LITERAL = 82;
  public static final int FLOAT_SUFFIX = 8;
  public static final int QUOTE = 36;
  public static final int DISP_COMMENT = 33;
  public static final int LINE_COMMENT = 61;
  public static final int LEFT_PAREN = 20;
  public static final int CHAR = 56;
  public static final int NUM_BIG_INT = 16;
  public static final int DO = 42;
  public static final int BACKQUOTE = 48;
  public static final int SLASH_LETTER = 63;
  public static final int BIG_SUFFIX = 7;
  public static final int DIGIT = 6;
  public static final int DISP_META = 27;
  public static final int symDOT = 76;
  public static final int HEX_DIGIT = 5;
  public static final int symATOM = 78;
  public static final int NULL_LITERAL = 90;
  public static final int STRING_LITERAL = 88;
  public static final int NUM_FLOAT = 17;
  public static final int DOUBLE_SUFFIX = 11;
  public static final int EOF = 0;
  public static final int INT_SUFFIX = 10;
  public static final int WRONG_STRING = 60;
  public static final int symIMPLICIT_ARG = 79;
  public static final int NoDigit1 = 67;
  public static final int symNS_SEP = 77;
  public static final int FLOAT_LITERAL = 83;
  public static final int LETTER = 62;
  public static final int HAT = 50;
  public static final int IDENT = 68;
  public static final int error = 1;
  public static final int WHITESPACE = 3;
  public static final int IF = 43;
  public static final int LEFT_SQUARE = 22;
  public static final int LONG_SUFFIX = 9;
  public static final int STRING_ESC = 57;
  public static final int KEYWORD = 69;
  public static final int COLON = 74;
  public static final int NUM_LONG = 15;
  public static final int DISP_SET = 31;
  public static final int DEFN = 38;
  public static final int DISP_EVAL = 32;
  public static final int TILDAAT = 54;
  public static final int CHAR_LITERAL = 87;
  public static final int SYMBOL = 75;
  public static final int EXPONENT = 12;
  public static final int DISP_REGEX = 29;
  public static final int SHARP_HAT = 49;
  public static final int BIG_DECIMAL_LITERAL = 85;
  public static final int LET_STAR = 46;
  public static final int NS = 44;
  public static final int RIGHT_CURLY = 25;
  public static final int STRING = 59;
  public static final int DISP_FN = 30;
  public static final int NUM_INT = 14;
  public static final int BIG_INT_LITERAL = 81;
  public static final int LET = 45;
  public static final int STRING_CONTENT = 58;
}

