
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 30 16:01:38 EDT 2009
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface ClojureSym {
  /* terminals */
  public static final int AT = 34;
  public static final int NUM_INT_PART = 13;
  public static final int NEWLINE = 2;
  public static final int RIGHT_PAREN = 21;
  public static final int RIGHT_SQUARE = 23;
  public static final int COMMA = 4;
  public static final int DOUBLE_LITERAL = 65;
  public static final int NUM_BIG_DECIMAL = 19;
  public static final int NUM_DOUBLE = 18;
  public static final int IMPLICIT_ARG = 32;
  public static final int WRONG_STRING_LITERAL = 70;
  public static final int INTEGER_LITERAL = 61;
  public static final int FALSE = 53;
  public static final int LEFT_CURLY = 24;
  public static final int NIL = 51;
  public static final int SHARP_CURLY = 26;
  public static final int TILDA = 33;
  public static final int RATIO = 67;
  public static final int ONE_NL = 36;
  public static final int BAD_CHARACTER = 54;
  public static final int OTHER_REDUCED = 47;
  public static final int OTHER = 45;
  public static final int TRUE = 52;
  public static final int SHARP = 29;
  public static final int NoDigit = 46;
  public static final int FLOAT_SUFFIX = 8;
  public static final int LONG_LITERAL = 63;
  public static final int QUOTE = 27;
  public static final int LINE_COMMENT = 42;
  public static final int LEFT_PAREN = 20;
  public static final int CHAR = 37;
  public static final int NUM_BIG_INT = 16;
  public static final int BACKQUOTE = 28;
  public static final int SLASH_LETTER = 44;
  public static final int BIG_SUFFIX = 7;
  public static final int DIGIT = 6;
  public static final int HEX_DIGIT = 5;
  public static final int symDOT = 57;
  public static final int symATOM = 59;
  public static final int NULL_LITERAL = 71;
  public static final int NUM_FLOAT = 17;
  public static final int STRING_LITERAL = 69;
  public static final int DOUBLE_SUFFIX = 11;
  public static final int EOF = 0;
  public static final int INT_SUFFIX = 10;
  public static final int WRONG_STRING = 41;
  public static final int symIMPLICIT_ARG = 60;
  public static final int NoDigit1 = 48;
  public static final int symNS_SEP = 58;
  public static final int FLOAT_LITERAL = 64;
  public static final int LETTER = 43;
  public static final int HAT = 31;
  public static final int IDENT = 49;
  public static final int error = 1;
  public static final int WHITESPACE = 3;
  public static final int LEFT_SQUARE = 22;
  public static final int LONG_SUFFIX = 9;
  public static final int STRING_ESC = 38;
  public static final int KEYWORD = 50;
  public static final int COLON = 55;
  public static final int NUM_LONG = 15;
  public static final int TILDAAT = 35;
  public static final int SYMBOL = 56;
  public static final int CHAR_LITERAL = 68;
  public static final int EXPONENT = 12;
  public static final int SHARP_HAT = 30;
  public static final int BIG_DECIMAL_LITERAL = 66;
  public static final int RIGHT_CURLY = 25;
  public static final int STRING = 40;
  public static final int NUM_INT = 14;
  public static final int BIG_INT_LITERAL = 62;
  public static final int STRING_CONTENT = 39;
}

