
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 30 22:52:19 EDT 2009
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface ClojureSym {
  /* terminals */
  public static final int AT = 42;
  public static final int NUM_INT_PART = 13;
  public static final int NEWLINE = 2;
  public static final int RIGHT_PAREN = 21;
  public static final int RIGHT_SQUARE = 23;
  public static final int COMMA = 4;
  public static final int DOUBLE_LITERAL = 73;
  public static final int NUM_BIG_DECIMAL = 19;
  public static final int DISP_DISCARD_FORM = 35;
  public static final int NUM_DOUBLE = 18;
  public static final int IMPLICIT_ARG = 40;
  public static final int WRONG_STRING_LITERAL = 78;
  public static final int INTEGER_LITERAL = 69;
  public static final int FALSE = 61;
  public static final int LEFT_CURLY = 24;
  public static final int NIL = 59;
  public static final int TILDA = 41;
  public static final int RATIO = 75;
  public static final int ONE_NL = 44;
  public static final int BAD_CHARACTER = 62;
  public static final int OTHER_REDUCED = 55;
  public static final int DISP_VAR = 28;
  public static final int DISPATCH = 26;
  public static final int OTHER = 53;
  public static final int TRUE = 60;
  public static final int NoDigit = 54;
  public static final int DISP_UNREADABLE = 34;
  public static final int LONG_LITERAL = 71;
  public static final int FLOAT_SUFFIX = 8;
  public static final int QUOTE = 36;
  public static final int DISP_COMMENT = 33;
  public static final int LINE_COMMENT = 50;
  public static final int LEFT_PAREN = 20;
  public static final int CHAR = 45;
  public static final int NUM_BIG_INT = 16;
  public static final int BACKQUOTE = 37;
  public static final int SLASH_LETTER = 52;
  public static final int BIG_SUFFIX = 7;
  public static final int DIGIT = 6;
  public static final int DISP_META = 27;
  public static final int HEX_DIGIT = 5;
  public static final int symDOT = 65;
  public static final int symATOM = 67;
  public static final int NULL_LITERAL = 79;
  public static final int STRING_LITERAL = 77;
  public static final int NUM_FLOAT = 17;
  public static final int DOUBLE_SUFFIX = 11;
  public static final int EOF = 0;
  public static final int INT_SUFFIX = 10;
  public static final int WRONG_STRING = 49;
  public static final int symIMPLICIT_ARG = 68;
  public static final int NoDigit1 = 56;
  public static final int symNS_SEP = 66;
  public static final int FLOAT_LITERAL = 72;
  public static final int LETTER = 51;
  public static final int HAT = 39;
  public static final int IDENT = 57;
  public static final int error = 1;
  public static final int WHITESPACE = 3;
  public static final int LEFT_SQUARE = 22;
  public static final int LONG_SUFFIX = 9;
  public static final int STRING_ESC = 46;
  public static final int KEYWORD = 58;
  public static final int COLON = 63;
  public static final int NUM_LONG = 15;
  public static final int DISP_SET = 31;
  public static final int DISP_EVAL = 32;
  public static final int TILDAAT = 43;
  public static final int CHAR_LITERAL = 76;
  public static final int SYMBOL = 64;
  public static final int EXPONENT = 12;
  public static final int DISP_REGEX = 29;
  public static final int SHARP_HAT = 38;
  public static final int BIG_DECIMAL_LITERAL = 74;
  public static final int RIGHT_CURLY = 25;
  public static final int STRING = 48;
  public static final int DISP_FN = 30;
  public static final int NUM_INT = 14;
  public static final int BIG_INT_LITERAL = 70;
  public static final int STRING_CONTENT = 47;
}

