/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReplManagerUI.java
 *
 * Created on Jan 20, 2010, 4:40:01 PM
 */

package org.enclojure.idetools.repl;

/**
 *
 * @author ericthor
 */
public class ReplManagerUI extends javax.swing.JPanel {

    /** Creates new form ReplManagerUI */
    public ReplManagerUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topLevelSplitPane = new javax.swing.JSplitPane();
        rightSplitPane = new javax.swing.JSplitPane();
        topRightPanel = new javax.swing.JPanel();
        defaultStartupScrollPane = new javax.swing.JScrollPane();
        startupAttributeTable = new javax.swing.JTable();
        jvmAdditionalArgsLabel = new javax.swing.JLabel();
        clojurePlatformLabel = new javax.swing.JLabel();
        clojurePlatformsComboBox = new javax.swing.JComboBox();
        jvmArgsScrollPane = new javax.swing.JScrollPane();
        jvmArgsList = new javax.swing.JList();
        jvmListToolBar = new javax.swing.JToolBar();
        addJvmArgsButton = new javax.swing.JButton();
        deleteJvmArgsButton = new javax.swing.JButton();
        defaultStartupAttribsLabel = new javax.swing.JLabel();
        clojureStartupListToolBar = new javax.swing.JToolBar();
        addClojureStartupButton = new javax.swing.JButton();
        deleteClojureStartupButton = new javax.swing.JButton();
        replTitleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bottomRightPanel = new javax.swing.JPanel();
        classpathsLabel = new javax.swing.JLabel();
        classpathTabbedPane = new javax.swing.JTabbedPane();
        classpathListPanel = new javax.swing.JPanel();
        classpathListToolBar = new javax.swing.JToolBar();
        classpathListMoveUpButton = new javax.swing.JButton();
        classpathListMoveDownButton = new javax.swing.JButton();
        classpathAddButton = new javax.swing.JButton();
        classpathRemoveButton = new javax.swing.JButton();
        classpathListScrollPane = new javax.swing.JScrollPane();
        classpathPathTable = new javax.swing.JTable();
        selectFromProjectsPanel = new javax.swing.JPanel();
        selectFromProjectsToolBar = new javax.swing.JToolBar();
        setProjectsSearchPathButton = new javax.swing.JButton();
        setSearchLibrarySpecButton = new javax.swing.JButton();
        projectListScrollPane = new javax.swing.JScrollPane();
        classpathSelectedProjectsTable = new javax.swing.JTable();
        leftPanel = new javax.swing.JPanel();
        replListToolBar = new javax.swing.JToolBar();
        addReplButton = new javax.swing.JButton();
        duplicateReplButton = new javax.swing.JButton();
        deleteReplButton = new javax.swing.JButton();
        replListScrollPane = new javax.swing.JScrollPane();
        replContextTable = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(32000, 32000));
        setPreferredSize(new java.awt.Dimension(1250, 850));
        setLayout(new java.awt.GridLayout());

        topLevelSplitPane.setDividerLocation(300);
        topLevelSplitPane.setOneTouchExpandable(true);

        rightSplitPane.setDividerLocation(300);
        rightSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        rightSplitPane.setMinimumSize(new java.awt.Dimension(0, 0));
        rightSplitPane.setOneTouchExpandable(true);
        rightSplitPane.setPreferredSize(new java.awt.Dimension(3284, 1538));

        topRightPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        startupAttributeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attribute", "Value", "ns"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        defaultStartupScrollPane.setViewportView(startupAttributeTable);

        jvmAdditionalArgsLabel.setText("Addition JVM args:");

        clojurePlatformLabel.setText("Clojure Platform");

        clojurePlatformsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clojurePlatformsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clojurePlatformsComboBoxActionPerformed(evt);
            }
        });

        jvmArgsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "-Xms512m", "-Xmx512m", "-server" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jvmArgsScrollPane.setViewportView(jvmArgsList);

        jvmListToolBar.setOrientation(1);
        jvmListToolBar.setRollover(true);

        addJvmArgsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Create.png"))); // NOI18N
        addJvmArgsButton.setMnemonic('\u2206');
        addJvmArgsButton.setToolTipText("Add Repl Context");
        addJvmArgsButton.setActionCommand("add-jvm-arg");
        addJvmArgsButton.setFocusable(false);
        addJvmArgsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addJvmArgsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jvmListToolBar.add(addJvmArgsButton);

        deleteJvmArgsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Delete.png"))); // NOI18N
        deleteJvmArgsButton.setMnemonic('\u00ae');
        deleteJvmArgsButton.setToolTipText("Delete Repl Context");
        deleteJvmArgsButton.setActionCommand("delete-jvm-arg");
        deleteJvmArgsButton.setFocusable(false);
        deleteJvmArgsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteJvmArgsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jvmListToolBar.add(deleteJvmArgsButton);

        defaultStartupAttribsLabel.setText("Default startup attributes");

        clojureStartupListToolBar.setOrientation(1);
        clojureStartupListToolBar.setRollover(true);

        addClojureStartupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Create.png"))); // NOI18N
        addClojureStartupButton.setMnemonic('\u221a');
        addClojureStartupButton.setToolTipText("Add Repl Context");
        addClojureStartupButton.setActionCommand("add-clojure-attribute");
        addClojureStartupButton.setFocusable(false);
        addClojureStartupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addClojureStartupButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clojureStartupListToolBar.add(addClojureStartupButton);

        deleteClojureStartupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Delete.png"))); // NOI18N
        deleteClojureStartupButton.setMnemonic('\u0153');
        deleteClojureStartupButton.setToolTipText("Delete Repl Context");
        deleteClojureStartupButton.setActionCommand("delete-clojure-attribute");
        deleteClojureStartupButton.setFocusable(false);
        deleteClojureStartupButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteClojureStartupButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clojureStartupListToolBar.add(deleteClojureStartupButton);

        replTitleLabel.setText("Settings for REPL");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.jdesktop.layout.GroupLayout topRightPanelLayout = new org.jdesktop.layout.GroupLayout(topRightPanel);
        topRightPanel.setLayout(topRightPanelLayout);
        topRightPanelLayout.setHorizontalGroup(
            topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topRightPanelLayout.createSequentialGroup()
                .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(replTitleLabel)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(topRightPanelLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(topRightPanelLayout.createSequentialGroup()
                                .add(clojurePlatformLabel)
                                .add(47, 47, 47)
                                .add(clojurePlatformsComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jvmAdditionalArgsLabel)
                            .add(topRightPanelLayout.createSequentialGroup()
                                .add(jvmListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(60, 60, 60)
                                .add(jvmArgsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 369, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(topRightPanelLayout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(defaultStartupAttribsLabel))
                            .add(topRightPanelLayout.createSequentialGroup()
                                .add(clojureStartupListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(defaultStartupScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 438, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE))
        );
        topRightPanelLayout.setVerticalGroup(
            topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(topRightPanelLayout.createSequentialGroup()
                .add(replTitleLabel)
                .add(12, 12, 12)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, topRightPanelLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(topRightPanelLayout.createSequentialGroup()
                                .add(4, 4, 4)
                                .add(clojurePlatformLabel))
                            .add(clojurePlatformsComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(6, 6, 6)
                        .add(jvmAdditionalArgsLabel)
                        .add(8, 8, 8)
                        .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jvmListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jvmArgsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.LEADING, topRightPanelLayout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 286, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(topRightPanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(defaultStartupAttribsLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(8, 8, 8)
                        .add(topRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(defaultStartupScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .add(clojureStartupListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
        );

        replTitleLabel.getAccessibleContext().setAccessibleName("Settings for REPL ");

        rightSplitPane.setTopComponent(topRightPanel);

        classpathsLabel.setText("Classpaths");

        classpathListToolBar.setOrientation(1);
        classpathListToolBar.setRollover(true);

        classpathListMoveUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Up.png"))); // NOI18N
        classpathListMoveUpButton.setMnemonic('\u00a8');
        classpathListMoveUpButton.setToolTipText("Move up");
        classpathListMoveUpButton.setActionCommand("moveup-classpath");
        classpathListMoveUpButton.setFocusable(false);
        classpathListMoveUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        classpathListMoveUpButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        classpathListToolBar.add(classpathListMoveUpButton);

        classpathListMoveDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Down.png"))); // NOI18N
        classpathListMoveDownButton.setMnemonic('\u00ac');
        classpathListMoveDownButton.setToolTipText("Move down");
        classpathListMoveDownButton.setActionCommand("movedown-classpath");
        classpathListMoveDownButton.setFocusable(false);
        classpathListMoveDownButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        classpathListMoveDownButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        classpathListToolBar.add(classpathListMoveDownButton);

        classpathAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Create.png"))); // NOI18N
        classpathAddButton.setMnemonic('\u00c5');
        classpathAddButton.setToolTipText("Add Path");
        classpathAddButton.setActionCommand("add-classpath");
        classpathAddButton.setFocusable(false);
        classpathAddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        classpathAddButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        classpathListToolBar.add(classpathAddButton);

        classpathRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Delete.png"))); // NOI18N
        classpathRemoveButton.setMnemonic('\u00ce');
        classpathRemoveButton.setToolTipText("Add Path");
        classpathRemoveButton.setActionCommand("delete-classpath");
        classpathRemoveButton.setFocusable(false);
        classpathRemoveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        classpathRemoveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        classpathListToolBar.add(classpathRemoveButton);

        classpathPathTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Path", "From"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        classpathListScrollPane.setViewportView(classpathPathTable);

        org.jdesktop.layout.GroupLayout classpathListPanelLayout = new org.jdesktop.layout.GroupLayout(classpathListPanel);
        classpathListPanel.setLayout(classpathListPanelLayout);
        classpathListPanelLayout.setHorizontalGroup(
            classpathListPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(classpathListPanelLayout.createSequentialGroup()
                .add(classpathListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(classpathListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
        );
        classpathListPanelLayout.setVerticalGroup(
            classpathListPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(classpathListPanelLayout.createSequentialGroup()
                .add(classpathListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .add(classpathListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        classpathTabbedPane.addTab("Classpath List", classpathListPanel);

        selectFromProjectsToolBar.setOrientation(1);
        selectFromProjectsToolBar.setRollover(true);

        setProjectsSearchPathButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Pinion.png"))); // NOI18N
        setProjectsSearchPathButton.setMnemonic('\u03c0');
        setProjectsSearchPathButton.setToolTipText("Project Paths");
        setProjectsSearchPathButton.setActionCommand("project-search-patterns");
        setProjectsSearchPathButton.setFocusable(false);
        setProjectsSearchPathButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setProjectsSearchPathButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selectFromProjectsToolBar.add(setProjectsSearchPathButton);

        setSearchLibrarySpecButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Tune.png"))); // NOI18N
        setSearchLibrarySpecButton.setMnemonic('\u00ac');
        setSearchLibrarySpecButton.setToolTipText("Lib Search Patterns");
        setSearchLibrarySpecButton.setActionCommand("lib-search-patterns");
        setSearchLibrarySpecButton.setFocusable(false);
        setSearchLibrarySpecButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setSearchLibrarySpecButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selectFromProjectsToolBar.add(setSearchLibrarySpecButton);

        classpathSelectedProjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Use", "Name", "Project Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        projectListScrollPane.setViewportView(classpathSelectedProjectsTable);

        org.jdesktop.layout.GroupLayout selectFromProjectsPanelLayout = new org.jdesktop.layout.GroupLayout(selectFromProjectsPanel);
        selectFromProjectsPanel.setLayout(selectFromProjectsPanelLayout);
        selectFromProjectsPanelLayout.setHorizontalGroup(
            selectFromProjectsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(selectFromProjectsPanelLayout.createSequentialGroup()
                .add(selectFromProjectsToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(projectListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE))
        );
        selectFromProjectsPanelLayout.setVerticalGroup(
            selectFromProjectsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(selectFromProjectsPanelLayout.createSequentialGroup()
                .add(selectFromProjectsToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 267, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .add(selectFromProjectsPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(projectListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        classpathTabbedPane.addTab("Select from Projects", selectFromProjectsPanel);

        org.jdesktop.layout.GroupLayout bottomRightPanelLayout = new org.jdesktop.layout.GroupLayout(bottomRightPanel);
        bottomRightPanel.setLayout(bottomRightPanelLayout);
        bottomRightPanelLayout.setHorizontalGroup(
            bottomRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, bottomRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(bottomRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bottomRightPanelLayout.createSequentialGroup()
                        .add(classpathsLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1049, Short.MAX_VALUE))
                    .add(bottomRightPanelLayout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(classpathTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bottomRightPanelLayout.setVerticalGroup(
            bottomRightPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bottomRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(classpathsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(classpathTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .add(15, 15, 15))
        );

        rightSplitPane.setBottomComponent(bottomRightPanel);

        topLevelSplitPane.setRightComponent(rightSplitPane);

        replListToolBar.setRollover(true);

        addReplButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Create.png"))); // NOI18N
        addReplButton.setMnemonic('\u00e5');
        addReplButton.setToolTipText("Add Repl Context");
        addReplButton.setActionCommand("add-repl");
        addReplButton.setFocusable(false);
        addReplButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addReplButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        replListToolBar.add(addReplButton);

        duplicateReplButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Copy.png"))); // NOI18N
        duplicateReplButton.setMnemonic('\u00e7');
        duplicateReplButton.setToolTipText("Duplicate REPl Context");
        duplicateReplButton.setActionCommand("copy-repl");
        duplicateReplButton.setFocusable(false);
        duplicateReplButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        duplicateReplButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        replListToolBar.add(duplicateReplButton);

        deleteReplButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/idetools/resources/Delete.png"))); // NOI18N
        deleteReplButton.setMnemonic('\u2202');
        deleteReplButton.setToolTipText("Delete Repl Context");
        deleteReplButton.setActionCommand("delete-repl");
        deleteReplButton.setFocusable(false);
        deleteReplButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteReplButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        replListToolBar.add(deleteReplButton);

        replContextTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Host", "Running"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        replListScrollPane.setViewportView(replContextTable);

        org.jdesktop.layout.GroupLayout leftPanelLayout = new org.jdesktop.layout.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftPanelLayout.createSequentialGroup()
                .add(replListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(replListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(leftPanelLayout.createSequentialGroup()
                .add(replListToolBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(replListScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
        );

        topLevelSplitPane.setLeftComponent(leftPanel);

        add(topLevelSplitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void clojurePlatformsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clojurePlatformsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clojurePlatformsComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addClojureStartupButton;
    public javax.swing.JButton addJvmArgsButton;
    public javax.swing.JButton addReplButton;
    public javax.swing.JPanel bottomRightPanel;
    public javax.swing.JButton classpathAddButton;
    public javax.swing.JButton classpathListMoveDownButton;
    public javax.swing.JButton classpathListMoveUpButton;
    public javax.swing.JPanel classpathListPanel;
    private javax.swing.JScrollPane classpathListScrollPane;
    public javax.swing.JToolBar classpathListToolBar;
    public javax.swing.JTable classpathPathTable;
    public javax.swing.JButton classpathRemoveButton;
    public javax.swing.JTable classpathSelectedProjectsTable;
    public javax.swing.JTabbedPane classpathTabbedPane;
    public javax.swing.JLabel classpathsLabel;
    public javax.swing.JLabel clojurePlatformLabel;
    public javax.swing.JComboBox clojurePlatformsComboBox;
    public javax.swing.JToolBar clojureStartupListToolBar;
    public javax.swing.JLabel defaultStartupAttribsLabel;
    public javax.swing.JScrollPane defaultStartupScrollPane;
    public javax.swing.JButton deleteClojureStartupButton;
    public javax.swing.JButton deleteJvmArgsButton;
    public javax.swing.JButton deleteReplButton;
    public javax.swing.JButton duplicateReplButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel jvmAdditionalArgsLabel;
    public javax.swing.JList jvmArgsList;
    public javax.swing.JScrollPane jvmArgsScrollPane;
    public javax.swing.JToolBar jvmListToolBar;
    public javax.swing.JPanel leftPanel;
    public javax.swing.JScrollPane projectListScrollPane;
    public javax.swing.JTable replContextTable;
    public javax.swing.JScrollPane replListScrollPane;
    public javax.swing.JToolBar replListToolBar;
    public javax.swing.JLabel replTitleLabel;
    public javax.swing.JSplitPane rightSplitPane;
    public javax.swing.JPanel selectFromProjectsPanel;
    public javax.swing.JToolBar selectFromProjectsToolBar;
    public javax.swing.JButton setProjectsSearchPathButton;
    public javax.swing.JButton setSearchLibrarySpecButton;
    public javax.swing.JTable startupAttributeTable;
    public javax.swing.JSplitPane topLevelSplitPane;
    public javax.swing.JPanel topRightPanel;
    // End of variables declaration//GEN-END:variables

}
