/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultiPaneFrame.java
 *
 * Created on Oct 5, 2009, 8:47:56 PM
 */

package org.enclojure.ide.repl;

/**
 *
 * @author ericthorsen
 */
public class MultiPaneFrame extends javax.swing.JFrame {

    /** Creates new form MultiPaneFrame */
    public MultiPaneFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));
        getContentPane().add(jScrollPane1);
        getContentPane().add(jScrollPane2);
        getContentPane().add(jScrollPane3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiPaneFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
