/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClojureReplDialog.java
 *
 * Created on Mar 8, 2009, 11:07:24 PM
 */

package org.enclojure.ide.nb.actions;

import clojure.lang.RT;
import clojure.lang.Var;
import org.openide.util.Exceptions;

/**
 *
 * @author magrawal
 */
public class CreateStandaloneReplDialog extends javax.swing.JDialog {

    static final Var nonProjectRepl =
      RT.var("org.enclojure.ide.nb.editor.repl-win", "start-stand-alone-repl-action");
    static final Var saveSettings =
      RT.var("org.enclojure.ide.settings.utils", "put-prefs");
    static final Var loadSettings =
      RT.var("org.enclojure.ide.settings.utils", "get-prefs");
    
    static final String ns_settings = "org.enclojure.ide.preferences.enclojure-options-category";
    /** Creates new form ClojureReplDialog */
    public CreateStandaloneReplDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            this.classPath.setText((String) loadSettings.invoke(ns_settings));
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

        errorLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javaArgs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        classPath = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        replName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javaArgs.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.javaArgs.text")); // NOI18N
        javaArgs.setEnabled(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.jLabel1.text")); // NOI18N
        jLabel1.setEnabled(false);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.jLabel2.text")); // NOI18N

        classPath.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.classPath.text")); // NOI18N

        connectButton.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.connectButton.text")); // NOI18N
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.errorLabel.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.jLabel4.text")); // NOI18N

        replName.setText(org.openide.util.NbBundle.getMessage(CreateStandaloneReplDialog.class, "CreateStandaloneReplDialog.replName.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel4)
                                    .add(jLabel2))
                                .add(50, 50, 50))
                            .add(layout.createSequentialGroup()
                                .add(connectButton)
                                .add(18, 18, 18)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(replName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .add(javaArgs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .add(classPath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(cancelButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(errorLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(replName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(javaArgs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(18, 18, 18)
                        .add(connectButton))
                    .add(layout.createSequentialGroup()
                        .add(classPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(errorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cancelButton))))
                .add(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        try {
            //Connect - if failed to connet - display red error on the dalog box
            nonProjectRepl.invoke(this.replName.getText(),
                    this.javaArgs.getText(),
                    this.classPath.getText());
            this.dispose();
        } catch (Exception ex) {
            this.errorLabel.setText(ex.getMessage());
            this.errorLabel.setVisible(true);
        }
        
        try {
            saveSettings.invoke(this.classPath.getText());
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

}//GEN-LAST:event_connectButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateStandaloneReplDialog dialog = new CreateStandaloneReplDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    public javax.swing.JTextField classPath;
    public javax.swing.JButton connectButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField javaArgs;
    public javax.swing.JTextField replName;
    // End of variables declaration//GEN-END:variables

}
