/*
(comment
*******************************************************************************
*    Copyright (c) ThorTech, L.L.C.. All rights reserved.
*    The use and distribution terms for this software are covered by the
*    GNU General Public License, version 2
*    (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html) with classpath
*    exception (http://www.gnu.org/software/classpath/license.html)
*    which can be found in the file GPL-2.0+ClasspathException.txt at the root
*    of this distribution.
*    By using this software in any fashion, you are agreeing to be bound by
*    the terms of this license.
*    You must not remove this notice, or any other, from this software.
*******************************************************************************
*    Author: Eric Thorsen
*******************************************************************************
)
*/
package org.enclojure.ide.preferences;

import clojure.lang.IFn;
import clojure.lang.RT;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.util.Exceptions;

public final class EnclojurePreferencesPanel extends javax.swing.JPanel {

    private final OptionsPanelController controller;
    IFn dispatcherFn = RT.var("org.enclojure.ide.preferences.platform-options","disp-hack");
    IFn startNonProjectREPLFn = RT.var("org.enclojure.ide.nb.editor.repl-win","start-stand-alone-repl-action");
    IFn tabbedStateChangedFn = RT.var("org.enclojure.ide.preferences.enclojure-options-category"
                                     ,"tabbed-panel-changed");
    public EnclojurePreferencesPanel(OptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }
    
    public static EnclojurePreferencesPanel create(OptionsPanelController controller) {
        return new EnclojurePreferencesPanel(controller);
    }

   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        warnOnReflectionCheckBox = new javax.swing.JCheckBox();
        printStackTraceCheckBox = new javax.swing.JCheckBox();
        usePrettyPrintCheckBox = new javax.swing.JCheckBox();
        printCircleCheckBox = new javax.swing.JCheckBox();
        printSharedCheckBox = new javax.swing.JCheckBox();
        printSuppressNamespaceCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        printLengthTextField = new javax.swing.JTextField();
        printLevelTextField = new javax.swing.JTextField();
        printRightMarginTextField = new javax.swing.JTextField();
        printMiserWidthTextField = new javax.swing.JTextField();
        printLinesTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        printBaseTextField = new javax.swing.JTextField();
        includeAllClasspathsCheckBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        clojurePlatformsComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jvmAdditionArgsTextField = new javax.swing.JTextField();
        printRadixCheckBox = new javax.swing.JCheckBox();
        enableLogging = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        enableIDEReplCheckBox = new javax.swing.JCheckBox();
        jPanelSettings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        platformScrollPane = new javax.swing.JScrollPane();
        platformList = new javax.swing.JList();
        removePlatformButton = new javax.swing.JButton();
        addPlatformButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        platformNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        classPathList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        removeClasspathButton = new javax.swing.JButton();
        addClasspathButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        setAsDefaultCheckBoxGuy = new javax.swing.JCheckBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, "jCheckBox1");

        setAutoscrolls(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), this, org.jdesktop.beansbinding.BeanProperty.create("preferredSize"));
        bindingGroup.addBinding(binding);

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${preferredSize}"), jTabbedPane1, org.jdesktop.beansbinding.BeanProperty.create("preferredSize"));
        bindingGroup.addBinding(binding);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_default_settings_for_repls_label")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_REPL_JAR_FileLocation")); // NOI18N

        warnOnReflectionCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(warnOnReflectionCheckBox, "*warn-on-reflection*");

        printStackTraceCheckBox.setSelected(true);
        printStackTraceCheckBox.setActionCommand("*print-stack-trace-on-error*");
        printStackTraceCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        printStackTraceCheckBox.setLabel("*print-stack-trace-on-error*");

        usePrettyPrintCheckBox.setSelected(true);
        usePrettyPrintCheckBox.setActionCommand("Use Pretty Print");
        usePrettyPrintCheckBox.setLabel("Use Pretty Print");

        printCircleCheckBox.setActionCommand("*print-stack-trace-on-error*");
        printCircleCheckBox.setLabel("*print-circle*");
        printCircleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printCircleCheckBoxActionPerformed(evt);
            }
        });

        printSharedCheckBox.setActionCommand("*print-stack-trace-on-error*");
        printSharedCheckBox.setEnabled(false);
        printSharedCheckBox.setLabel("*print-shared*");

        printSuppressNamespaceCheckBox.setActionCommand("*print-stack-trace-on-error*");
        printSuppressNamespaceCheckBox.setLabel("*print-suppress-namespace*");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "*print-length*");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "*print-level*");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, "*print-right-margin*");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, "*print-miser-width*");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, "*print-lines*");

        printLengthTextField.setText("20");
        printLengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLengthTextFieldActionPerformed(evt);
            }
        });

        printLevelTextField.setText("5");
        printLevelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLevelTextFieldActionPerformed(evt);
            }
        });

        printRightMarginTextField.setText("20");
        printRightMarginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRightMarginTextFieldActionPerformed(evt);
            }
        });

        printMiserWidthTextField.setText("40");
        printMiserWidthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMiserWidthTextFieldActionPerformed(evt);
            }
        });

        printLinesTextField.setText("20");
        printLinesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLinesTextFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, "*print-base*");

        printBaseTextField.setText("10");
        printBaseTextField.setEnabled(false);
        printBaseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBaseTextFieldActionPerformed(evt);
            }
        });

        includeAllClasspathsCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(includeAllClasspathsCheckBox, "Include classpaths from all open projects");
        includeAllClasspathsCheckBox.setActionCommand("*print-stack-trace-on-error*");
        includeAllClasspathsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                includeAllClasspathsCheckBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 2, 13));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_uses_pprint_label")); // NOI18N
        jLabel11.setToolTipText(org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_REPL_JAR_FileLocation")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_for_standalone_repl_label")); // NOI18N
        jLabel12.setToolTipText(org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_REPL_JAR_FileLocation")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, "Clojure Platform");

        clojurePlatformsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 2, 13));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_hint_use_platform_manager_label")); // NOI18N
        jLabel14.setToolTipText(org.openide.util.NbBundle.getMessage(EnclojurePreferencesPanel.class, "Settings_REPL_JAR_FileLocation")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, "Addition JVM args:");

        jvmAdditionArgsTextField.setText("-Xms512m -Xmx512m");
        jvmAdditionArgsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvmAdditionArgsTextFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(printRadixCheckBox, "*print-radix*");
        printRadixCheckBox.setActionCommand("*print-stack-trace-on-error*");
        printRadixCheckBox.setEnabled(false);
        printRadixCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRadixCheckBoxActionPerformed(evt);
            }
        });

        enableLogging.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(enableLogging, "Enable logging");
        enableLogging.setActionCommand("*print-stack-trace-on-error*");
        enableLogging.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        enableIDEReplCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(enableIDEReplCheckBox, "Enable IDE Repl");
        enableIDEReplCheckBox.setToolTipText("Enable the IDE REPL in the Window Menu");
        enableIDEReplCheckBox.setActionCommand("*print-stack-trace-on-error*");
        enableIDEReplCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableIDEReplCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(clojurePlatformsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(includeAllClasspathsCheckBox))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warnOnReflectionCheckBox)
                            .addComponent(printStackTraceCheckBox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(printLevelTextField)
                                    .addComponent(printLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(enableLogging))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(printSharedCheckBox)
                                    .addComponent(printSuppressNamespaceCheckBox)
                                    .addComponent(printCircleCheckBox)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(printRightMarginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(printLinesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(printMiserWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(printBaseTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(printRadixCheckBox))
                                .addGap(276, 276, 276))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(usePrettyPrintCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(90, 90, 90))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jvmAdditionArgsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(244, 244, 244))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addGap(488, 488, 488))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableIDEReplCheckBox)
                .addContainerGap(1044, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usePrettyPrintCheckBox)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(printRadixCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printCircleCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printSharedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printSuppressNamespaceCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(printRightMarginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(printLinesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(printMiserWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(warnOnReflectionCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printStackTraceCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enableLogging)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(printLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(printLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jvmAdditionArgsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(clojurePlatformsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(includeAllClasspathsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enableIDEReplCheckBox)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("REPL Settings", jPanel2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "Clojure Platforms");

        platformList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        platformList.setName("plaftormList"); // NOI18N
        platformList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                platformListPropertyChange(evt);
            }
        });
        platformList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                platformListValueChanged(evt);
            }
        });
        platformScrollPane.setViewportView(platformList);

        org.openide.awt.Mnemonics.setLocalizedText(removePlatformButton, "Remove");
        removePlatformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePlatformButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(addPlatformButton, "Add Platform");
        addPlatformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatformButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, "Platform Name");

        platformNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                platformNameTextFieldKeyTyped(evt);
            }
        });

        classPathList.setName("classPathList"); // NOI18N
        classPathList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                classPathListPropertyChange(evt);
            }
        });
        classPathList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                classPathListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(classPathList);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, "Classpaths");

        org.openide.awt.Mnemonics.setLocalizedText(removeClasspathButton, "Remove");
        removeClasspathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClasspathButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(addClasspathButton, "Add");
        addClasspathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClasspathButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13));
        errorLabel.setForeground(new java.awt.Color(204, 0, 0));

        org.openide.awt.Mnemonics.setLocalizedText(setAsDefaultCheckBoxGuy, "Set as default:");
        setAsDefaultCheckBoxGuy.setToolTipText("Set this platform as the default platform for REPLs and new projects.");
        setAsDefaultCheckBoxGuy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setAsDefaultCheckBoxGuy.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        setAsDefaultCheckBoxGuy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setAsDefaultCheckBoxGuyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(platformScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(addPlatformButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removePlatformButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSettingsLayout.createSequentialGroup()
                            .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSettingsLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(platformNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(setAsDefaultCheckBoxGuy))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                                .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE))
                            .addGap(0, 0, 0))
                        .addGroup(jPanelSettingsLayout.createSequentialGroup()
                            .addComponent(addClasspathButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(removeClasspathButton)
                            .addContainerGap()))
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platformScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removePlatformButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPlatformButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(platformNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setAsDefaultCheckBoxGuy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addClasspathButton)
                            .addComponent(removeClasspathButton))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clojure Platforms", jPanelSettings);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void removePlatformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePlatformButtonActionPerformed
        try {
            dispatcherFn.invoke("removePlatformButtonActionPerformed", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_removePlatformButtonActionPerformed

    private void addPlatformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatformButtonActionPerformed
                try {
            dispatcherFn.invoke("addPlatformButtonActionPerformed", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_addPlatformButtonActionPerformed

    private void platformListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_platformListValueChanged
                try {
            dispatcherFn.invoke("platformListValueChanged", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_platformListValueChanged

    private void addClasspathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClasspathButtonActionPerformed
                try {
            dispatcherFn.invoke("addClasspathButtonActionPerformed", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_addClasspathButtonActionPerformed

    private void removeClasspathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClasspathButtonActionPerformed
                try {
            dispatcherFn.invoke("removeClasspathButtonActionPerformed", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_removeClasspathButtonActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
               try {
            tabbedStateChangedFn.invoke( this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void classPathListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_classPathListValueChanged
                try {
            dispatcherFn.invoke("classPathListValueChanged", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_classPathListValueChanged

    private void platformNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_platformNameTextFieldKeyTyped
                try {
            dispatcherFn.invoke("platformNameTextFieldKeyTyped", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_platformNameTextFieldKeyTyped

    private void setAsDefaultCheckBoxGuyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setAsDefaultCheckBoxGuyItemStateChanged
                try {
            dispatcherFn.invoke("setAsDefaultCheckBoxGuyItemStateChanged", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_setAsDefaultCheckBoxGuyItemStateChanged

    private void classPathListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_classPathListPropertyChange
                try {
            dispatcherFn.invoke("classPathListPropertyChange", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_classPathListPropertyChange

    private void platformListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_platformListPropertyChange
                try {
            dispatcherFn.invoke("platformListPropertyChange", this, evt);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_platformListPropertyChange

    private void printCircleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printCircleCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printCircleCheckBoxActionPerformed

    private void printLengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printLengthTextFieldActionPerformed

    private void printLevelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLevelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printLevelTextFieldActionPerformed

    private void printRightMarginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRightMarginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printRightMarginTextFieldActionPerformed

    private void printMiserWidthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMiserWidthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printMiserWidthTextFieldActionPerformed

    private void printLinesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLinesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printLinesTextFieldActionPerformed

    private void printBaseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBaseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBaseTextFieldActionPerformed

    private void includeAllClasspathsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_includeAllClasspathsCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_includeAllClasspathsCheckBoxActionPerformed

    private void jvmAdditionArgsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvmAdditionArgsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvmAdditionArgsTextFieldActionPerformed

    private void printRadixCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRadixCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printRadixCheckBoxActionPerformed

    private void enableIDEReplCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableIDEReplCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableIDEReplCheckBoxActionPerformed

                                                      
    private void jCheckBoxUseEmbeddedClojureActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

  
    public boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addClasspathButton;
    public javax.swing.JButton addPlatformButton;
    public javax.swing.JList classPathList;
    public javax.swing.JComboBox clojurePlatformsComboBox;
    public javax.swing.JCheckBox enableIDEReplCheckBox;
    public javax.swing.JCheckBox enableLogging;
    public javax.swing.JLabel errorLabel;
    public javax.swing.JCheckBox includeAllClasspathsCheckBox;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanelSettings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jvmAdditionArgsTextField;
    public javax.swing.JList platformList;
    public javax.swing.JTextField platformNameTextField;
    public javax.swing.JScrollPane platformScrollPane;
    public javax.swing.JTextField printBaseTextField;
    public javax.swing.JCheckBox printCircleCheckBox;
    public javax.swing.JTextField printLengthTextField;
    public javax.swing.JTextField printLevelTextField;
    public javax.swing.JTextField printLinesTextField;
    public javax.swing.JTextField printMiserWidthTextField;
    public javax.swing.JCheckBox printRadixCheckBox;
    public javax.swing.JTextField printRightMarginTextField;
    public javax.swing.JCheckBox printSharedCheckBox;
    public javax.swing.JCheckBox printStackTraceCheckBox;
    public javax.swing.JCheckBox printSuppressNamespaceCheckBox;
    public javax.swing.JButton removeClasspathButton;
    public javax.swing.JButton removePlatformButton;
    public javax.swing.JCheckBox setAsDefaultCheckBoxGuy;
    public javax.swing.JCheckBox usePrettyPrintCheckBox;
    public javax.swing.JCheckBox warnOnReflectionCheckBox;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
