/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CljNavigatorViewPanel.java
 *
 * Created on Mar 3, 2009, 9:48:36 AM
 */

package org.enclojure.ide.navigator.views;

/**
 *
 * @author ericthorsen
 */
public class CljNavigatorViewPanel extends javax.swing.JPanel {

    /** Creates new form CljNavigatorViewPanel */
    public CljNavigatorViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonAlphaSort = new javax.swing.JToggleButton();
        jToggleButtonSortPos = new javax.swing.JToggleButton();
        jToggleButtonExpandAll = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();

        jToolBar1.setRollover(true);

        jToggleButtonAlphaSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/ide/resources/sortAlpha.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/enclojure/ide/Bundle"); // NOI18N
        jToggleButtonAlphaSort.setToolTipText(bundle.getString("SORT_APLHA")); // NOI18N
        jToggleButtonAlphaSort.setFocusable(false);
        jToggleButtonAlphaSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonAlphaSort.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonAlphaSort);

        jToggleButtonSortPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/ide/resources/sortPosition.png"))); // NOI18N
        jToggleButtonSortPos.setToolTipText(bundle.getString("SORT_POSITION")); // NOI18N
        jToggleButtonSortPos.setFocusable(false);
        jToggleButtonSortPos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonSortPos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonSortPos);

        jToggleButtonExpandAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/enclojure/ide/resources/expandall.gif"))); // NOI18N
        jToggleButtonExpandAll.setToolTipText("Expand/Collapse Nodes");
        jToggleButtonExpandAll.setFocusable(false);
        jToggleButtonExpandAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonExpandAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonExpandAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane;
    public javax.swing.JToggleButton jToggleButtonAlphaSort;
    public javax.swing.JToggleButton jToggleButtonExpandAll;
    public javax.swing.JToggleButton jToggleButtonSortPos;
    public javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
